export const data = {
  products: [
    // {id:'1', name:'Pita Bread', price:'12000L.L.', image:""},{id:'12', name:'Birthday Cake', price:'75000L.L.', image:"./products/"},
    // {id:'2', name:'Brown Pita Bread', price:'15000L.L.', image:"./products/brownpita"},{id:'20', name:'Fuit Filled Layered Cake', price:'180000L.L.', image:"./products/"},
    // {id:'3', name:'Markuk', price:'10000L.L.', image:"./products/"},{id:'21', name:'Chocolate Cortina Cake', price:'200000L.L.', image:"./products/"},
    // {id:'4', name:'Tannour', price:'13500L.L.', image:"./products/"},{id:'22', name:'Cupcake', price:'6000L.L.', image:"./products/"},
    // {id:'5', name:'Oat Bread', price:'14000L.L.', image:"./products/"},{id:'23', name:'Mini-cake', price:'4000L.L.', image:"./products/"},
    // {id:'6', name:'Whole Grain Bread', price:'10000L.L.', image:"./products/"},{id:'24', name:'Croissant', price:'6000L.L.', image:"./products/"},
    // {id:'7', name:'Wheat Bread', price:'12000L.L.', image:"./products/"},{id:'25', name:'Donut', price:'6000L.L.', image:"./products/"},
    // {id:'8', name:'Corn Bread', price:'11000L.L.', image:"./products/"},{id:'26', name:'Sablet', price:'7000L.L.', image:"./products/"},
    // {id:'9', name:'Baguette', price:'12500L.L.', image:"./products/"},{id:'27', name:'Eclairs', price:'3000L.L.', image:"./products/"},
    // {id:'10', name:'Kaak', price:'7000L.L.', image:"./products/"},{id:'28', name:'Choux', price:'3000L.L.', image:"./products/"},
    // {id:'11', name:'Iraqi Sammoon', price:'10000L.L.', image:"./products/"},{id:'29', name:'Pies', price:'5000L.L.', image:"./products/"},
    // { id: '12', name: 'Pain au lait', price: '8000L.L.', image: './products/' },
    { id: '30', name: 'Baklawa', price: '150000L.L.', image: '/Product/10.jpg' },
    // {id:'13', name:'White Bread Loaf', price:'10000L.L', image:"./products/"},{id:'31', name:'Maddat', price:'18000L.L.', image:"./products/"},
    // {id:'14', name:'Brown Bread Loaf', price:'12000ll', image:"./products/"},{id:'32', name:'Shaabiyat', price:'23000ll', image:"./products/"},
    // {id:'15', name:'Burger Buns', price:'16000ll', image:"./products/"},{id:'33', name:'Sfouf', price:'21000ll', image:"./products/"},
    // {id:'16', name:'Ciabatta', price:'20000ll', image:"./products/"},{id:'34', name:'Mafrouka ', price:'15000ll', image:"./products/"},
    // {id:'17', name:'Focaccia', price:'18000ll', image:"./products/"},{id:'35', name:'Nammoura', price:'27000ll', image:"./products/"},
    // {id:'18', name:'Loaf Cake', price:'25000ll', image:"./products/"},{id:'36', name:'Mshabak', price:'25000ll', image:"./products/"},
    // {id:'37', name:'Floaties', price:'12000ll', image:"./products/"},{id:'38', name:'Katayef', price:'23000ll', image:"./products/"},

    // {id:'39', name:'Pita Bread', price:'12000L.L.', image:"./products/"},{id:'12', name:'Christmas Logs', price:'75000L.L.', image:"./products/"},
    // {id:'40', name:'Brown Pita Bread', price:'15000L.L.', image:"./products/"},{id:'20', name:'Fuit Filled Layered Cake', price:'180000L.L.', image:"./products/"},
    // {id:'41', name:'Markuk', price:'10000L.L.', image:"./products/"},{id:'21', name:'Chocolate Cortina Cake', price:'200000L.L.', image:"./products/"},
    // {id:'42', name:'Tannour', price:'13500L.L.', image:"./products/"},{id:'22', name:'Cupcake', price:'6000L.L.', image:"./products/"},
    // {id:'43', name:'Oat Bread', price:'14000L.L.', image:"./products/"},{id:'23', name:'Mini-cake', price:'4000L.L.', image:"./products/"},
    // {id:'44', name:'Whole Grain Bread', price:'10000L.L.', image:"./products/"},{id:'24', name:'Croissant', price:'6000L.L.', image:"./products/"},
    // {id:'45', name:'Wheat Bread', price:'12000L.L.', image:"./products/"},{id:'25', name:'Donut', price:'6000L.L.', image:"./products/"},
    // {id:'46', name:'Corn Bread', price:'11000L.L.', image:"./products/"},{id:'26', name:'Sablet', price:'7000L.L.', image:"./products/"},
    // {id:'47', name:'Baguette', price:'12500L.L.', image:"./products/"},{id:'27', name:'Eclairs', price:'3000L.L.', image:"./products/"},
    // {id:'48', name:'Kaak', price:'7000L.L.', image:"./products/"},{id:'28', name:'Choux', price:'3000L.L.', image:"./products/"},
    // {id:'49', name:'Iraqi Sammoon', price:'10000L.L.', image:"./products/"},{id:'29', name:'Pies', price:'5000L.L.', image:"./products/"},
    // {id:'50', name:'Pain au lait', price:'8000L.L.', image:"./products/"},{id:'30', name:'Baklawa', price:'150000L.L.', image:"./products/"},
    // {id:'51', name:'White Bread Loaf', price:'10000L.L', image:"./products/"},{id:'31', name:'Maddat', price:'18000L.L.', image:"./products/"},
    // {id:'52', name:'Brown Bread Loaf', price:'12000ll', image:"./products/"},{id:'32', name:'Shaabiyat', price:'23000ll', image:"./products/"},
    // {id:'53', name:'Burger Buns', price:'16000ll', image:"./products/"},{id:'33', name:'Sfouf', price:'21000ll', image:"./products/"},
    // {id:'54', name:'Ciabatta', price:'20000ll', image:"./products/"},{id:'34', name:'Mafrouka ', price:'15000ll', image:"./products/"},
    // {id:'17', name:'Focaccia', price:'18000ll', image:"./products/"},{id:'35', name:'Nammoura', price:'27000ll', image:"./products/"},
    // {id:'18', name:'Loaf Cake', price:'25000ll', image:"./products/"},{id:'36', name:'Mshabak', price:'25000ll', image:"./products/"},
    // {id:'37', name:'Floaties', price:'12000ll', image:"./products/"},{id:'38', name:'Katayef', price:'23000ll', image:"./products/"}
  ],
}

export default data
